// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {querier} from '../models';
import {http} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Hi(arg1:string):Promise<string>;

export function SendRequest(arg1:querier.SimpleQuery):Promise<http.Response>;
